"""add report_sequences table

Revision ID: dc2cb194bdcf
Revises: a70ba45c0406
Create Date: 2026-09-24 16:47:15.887628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2cb194bdcf'
down_revision: Union[str, None] = 'a70ba45c0406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_sequences')
    # ### end Alembic commands ###
